<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>false</IsAotCompatible>
    <EnablePackageValidation>true</EnablePackageValidation>
    <PackageValidationBaselineVersion>0.1.0-preview.2.1.1</PackageValidationBaselineVersion>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>Pure.RelationalSchema.Storage.PureQL.Projection</PackageId>
    <RootNamespace>Pure.RelationalSchema.Storage.PureQL.Projection</RootNamespace>
    <AssemblyName>Pure.RelationalSchema.Storage.PureQL.Projection</AssemblyName>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/kudima03/Pure.RelationalSchema.Storage.PureQL.Projection</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pure.Primitives" Version="3.6.5" />
    <PackageReference Include="Pure.RelationalSchema" Version="2.0.3" />
    <PackageReference Include="Pure.RelationalSchema.HashCodes" Version="3.3.0" />
    <PackageReference Include="Pure.RelationalSchema.Storage" Version="0.1.0-preview.8.0.0" />
    <PackageReference Include="PureQL.CSharp.Model" Version="0.1.0-preview.11.0.1" />
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
    <PackageReference Include="Pure.Collections.Generic" Version="0.1.0-preview.3.0.0" />
  </ItemGroup>
</Project>
